// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_2_adding_heading_content_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_2_adding_heading_content_status));
        
        string IMigrationMetadata.Id
        {
            get { return "202105272152089_mig_2_adding_heading_content_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
